version: "3"
services:
  db:
    image: mysql:8.0
    container_name: industria-db
    restart: unless-stopped
    # command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - industria
    # depends_on:
    #   - app
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 3306:3306
      # SERVICE_TAGS: dev
      # SERVICE_NAME: mysql



  # nginx:
  #   image: nginx:alpine
  #   container_name: industria-nginx
  #   restart: unless-stopped
  #   ports:
  #     - 8000:80
  #     - 8001:81
  #     - 8002:82
  #   volumes:
  #     - ./:/var/www:delegated
  #     - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - industria


networks:
  industria:
    driver: bridge

volumes:
  db-volume:
